- DetResizeForTest:
    limit_side_len: 960
    limit_type: max
- NormalizeImage:
    mean:
    - 0.485
    - 0.456
    - 0.406
    order: hwc
    scale: 1./255.
    std:
    - 0.229
    - 0.224
    - 0.225
- ToCHWImage: null
- KeepKeys:
    keep_keys:
    - image
    - shape
